name:               "Valeria Chiesa"
description:        "Ph.D. candidate in Signal and Image Processing"

url:                ""
author:             "thinker3197"
email:              "jhondoe@abc.com"
gravatar_hash:      "205e460b479e2e5b48aec07710c08d50"
twitter:            "jhondoe"
email:              "jhondoe@abc.com"
github:             "jhondoe"
pinterest:          "jhondoe"
linkedin:           "jhondoe"
facebook:           "jhondoe"

disqus_shortname:   "thinker3197"

background:         "/images/BKG.jpg" 

paginate:           5
paginate_path:      "/page:num/"

baseurl:            ""
permalink:          /:year/:month/:day/:title/

markdown:           kramdown

nav:
  - name:           "CV"
    href:           "/about"
  - name:           "My publications"
    href:           "/publications"
  - name:           "Projects"
    href:           "/project"
  - name:           "Experience"
    href:           "/experience"
  - name:           "Contacts"
    href:           "/contact"

sass:
  style:            :compressed

defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-paginate